version: "3.4"

services:
  fl-api:
    image: fl-api
    build:
      context: ./fl-api
      dockerfile: Dockerfile
    ports:
      - 5002:5002
  fl-client:
    image: fl-client
    build:
      context: ./fl-client
      dockerfile: Dockerfile
    ports:
      - 4002:4002
